version: '3.8'

services:
  gravitypos:
    image: ${DOCKER_IMAGE:-ghcr.io/dafariski77/pos:latest}
    container_name: gravitypos-app
    restart: unless-stopped
    ports:
      - "3001:3001"
    env_file:
      - .env
