version: '3.8'

services:
  gravitypos:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gravitypos-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env
